import type { Metadata } from "next";
import { PT_Sans} from "next/font/google";
import "@/app/globals.css";
import { getCurrentUser } from "@/auth/nextjs/currentUser";



const ptSans = PT_Sans({
  variable: "--font-pt-sans", 
  subsets: ["latin"],
  weight: "400"
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body
        className={`${ptSans.variable} antialiased bg-base-100 shadow-sm text-[#42B9FC]`} 
      >
        {children}
      </body>
    </html>
  );
}
